language: cpp
compiler:
    - g++-7

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - build-essential
            - g++-7
            - libgtk-3-dev
            - libpulse-dev
            - nvidia-cuda-toolkit

before_install:
    - export CXX=g++-7
    - cuda-install-samples-9.1.sh ~

script:
    - make
