language: cpp

include:
    - os: linux
      addons:
          apt:
              sources:
                  - ubuntu-toolchain-r-test
              packages:
                  - g++-7
env:
    global:
          - CC=gcc-7 
          - CXX=g++-7

script:
    - make
