language: cpp
compiler:
    - g++-7

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - build-essential
            - g++-7
            - libgtk-3-dev
            - libpulse-dev
            - nvidia-cuda-toolkit
            - nvidia-cuda-dev
            - nvidia-profiler
            - cuda-samples

before_install:
    - export CXX=g++-7
    - ls -r /*
    - $(ls /usr/local/cuda/bin/cuda-install-samples*.sh) ~

script:
    - make
